services:
  mongodb:
    image: mongo:latest
    container_name: dx_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - dx_db:/data/db
    networks:
      - dx
    env_file:
      - .env

  redis:
    image: 'redis:latest'
    container_name: dx_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - dx_redis:/data
    networks:
      - dx

volumes:
  dx_db:
    external: true
  dx_redis:
    external: true

networks:
  dx:
    external: true
